apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bnsi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0061-tenant/tkrw-pr712-0075-0061-app/devfile-sample-bnsi@sha256:44fabd211b31a75e5f80b76202a677ffe305340d059e020e8f129a54caa04c6f
        name: my-nodejs
        resources: {}
status: {}
